// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Adresse {
	/**
	 * 
	 */
	private Utilisateur utilisateur;

	
}
