// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/************************************************************/
/**
 * 
 */
public class BonCommande {
	/**
	 * id
	 */
	private Integer id_bonCommande;
	/**
	 * intervenants
	 */
	private String nom_commercial_commande, nom_acheteur_commande, nom_preparateur_commande, nom_delivreur_commande, nom_receptionneur_commande;
	/**
	 * dates
	 */
	private Date date_creation_commande, date_preparation_commande, date_retrait_commande;
	/**
	 * accepter_ou_refuser_commande
	 */
	private boolean accepter_ou_refuser_commande; 
	/**
	 * relation one to many table lignecommandes
	 */
	private List<LigneCommande> liste_lignes;
	//private List<Produit> list_produits; // si Produit a pour attribut une quantité/poids à préciser pour cette commande
	// ou 
	private HashMap<Produit, Integer> produit_quantite; // map produit & quantité à préciser en dehors du produit
	/**
	 *  
	 */
	private Entreprise entreprise; // acheteur 
	private Integer fk_id_entreprise;
	/**
	 *  
	 */
	private Type_commande type_commande; // 
	private Integer fk_id_type_commande;
	/**
	 * relation one to many 
	 */
	private List<Utilisateur> utilisateurs;  // delivreur // preparateur // commercial
	// ou pour palier au problème de conception en bdd. Le probleme est, comment être sur d'identifier 
	// le bon intervenant sur la commande par son nom, la conception aurait été :
	// 1 par l'identifiant
	// 2 en créant une table en relation de N intervenants(commercial, préparateur..etc) à 1 commande
	
	//  solution avec une Map lier un utilisateur et son role à la commande 
	private Map<Utilisateur, Role> liste_intervenants;
	
	public BonCommande() {}
	
	public BonCommande(Integer id_bonCommande, Date date_creation_commande, Date date_preparation_commande,
			Date date_retrait_commande, List<LigneCommande> liste_lignes, HashMap<Produit, Integer> produit_quantite,
			Entreprise entreprise, Integer fk_id_entreprise, Type_commande type_commande, Integer fk_id_commande,
			List<Utilisateur> utilisateurs) {
		
		this.id_bonCommande = id_bonCommande;
		this.date_creation_commande = date_creation_commande;
		this.date_preparation_commande = date_preparation_commande;
		this.date_retrait_commande = date_retrait_commande;
		this.liste_lignes = liste_lignes;
		//this.produit_quantite = produit_quantite;
		this.entreprise = entreprise;
		this.fk_id_entreprise = fk_id_entreprise;
		this.type_commande = type_commande;
		this.fk_id_type_commande = fk_id_commande;
		this.utilisateurs = utilisateurs;
	}

	public Integer getId_bonCommande() {
		return id_bonCommande;
	}

	public void setId_bonCommande(Integer id_bonCommande) {
		this.id_bonCommande = id_bonCommande;
	}
	
	
	public boolean isAccepter_ou_refuser_commande() {
		return accepter_ou_refuser_commande;
	}

	public void setAccepter_ou_refuser_commande(boolean accepter_ou_refuser_commande) {
		this.accepter_ou_refuser_commande = accepter_ou_refuser_commande;
	}

	public String getNom_commercial_commande() {
		return nom_commercial_commande;
	}

	public void setNom_commercial_commande(String nom_commercial_commande) {
		this.nom_commercial_commande = nom_commercial_commande;
	}

	public String getNom_acheteur_commande() {
		return nom_acheteur_commande;
	}

	public void setNom_acheteur_commande(String nom_acheteur_commande) {
		this.nom_acheteur_commande = nom_acheteur_commande;
	}

	public String getNom_preparateur_commande() {
		return nom_preparateur_commande;
	}

	public void setNom_preparateur_commande(String nom_preparateur_commande) {
		this.nom_preparateur_commande = nom_preparateur_commande;
	}

	public String getNom_delivreur_commande() {
		return nom_delivreur_commande;
	}

	public void setNom_delivreur_commande(String nom_delivreur_commande) {
		this.nom_delivreur_commande = nom_delivreur_commande;
	}

	public String getNom_receptionneur_commande() {
		return nom_receptionneur_commande;
	}

	public void setNom_receptionneur_commande(String nom_receptionneur_commande) {
		this.nom_receptionneur_commande = nom_receptionneur_commande;
	}

	public Date getDate_creation_commande() {
		return date_creation_commande;
	}

	public void setDate_creation_commande(Date date_creation_commande) {
		this.date_creation_commande = date_creation_commande;
	}

	public Date getDate_preparation_commande() {
		return date_preparation_commande;
	}

	public void setDate_preparation_commande(Date date_preparation_commande) {
		this.date_preparation_commande = date_preparation_commande;
	}

	public Date getDate_retrait_commande() {
		return date_retrait_commande;
	}

	public void setDate_retrait_commande(Date date_retrait_commande) {
		this.date_retrait_commande = date_retrait_commande;
	}

	public List<LigneCommande> getListe_lignes() {
		return liste_lignes;
	}

	public void setliste_lignes(List<LigneCommande> liste_lignes) {
		this.liste_lignes = liste_lignes;
	}

//	public HashMap<Produit, Integer> getProduit_quantite() {
//		return produit_quantite;
//	}
//
//	public void setProduit_quantite(HashMap<Produit, Integer> produit_quantite) {
//		this.produit_quantite = produit_quantite;
//	}

	public Entreprise getEntreprise() {
		return entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
		
	      if (entreprise != null)
	      {
	         this.fk_id_entreprise = entreprise.getId_entreprise();    
	      }
	}
	

	public Integer getFk_id_entreprise() {
		return fk_id_entreprise;
	}

	public void setFk_id_entreprise(Integer fk_id_entreprise) {
		this.fk_id_entreprise = fk_id_entreprise;
	}

	public Type_commande getType_commande() {
		return type_commande;
	}

	public void setType_commande(Type_commande type_commande) {
		this.type_commande = type_commande;
		
	      if (type_commande != null)
	      {
	         this.fk_id_type_commande = type_commande.getId_type_commande();    
	      }
	}
	
	public Integer getFk_id_type_commande() {
		return fk_id_type_commande;
	}

	public void setFk_id_type_commande(Integer fk_id_type_commande) {
		this.fk_id_type_commande = fk_id_type_commande;
	}

	public List<Utilisateur> getUtilisateurs() {
		return utilisateurs;
	}

	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	@Override
	public String toString() {
		return "BonCommande [id_bonCommande=" + id_bonCommande + ", nom_commercial_commande=" + nom_commercial_commande
				+ ", nom_acheteur_commande=" + nom_acheteur_commande + ", nom_preparateur_commande="
				+ nom_preparateur_commande + ", nom_delivreur_commande=" + nom_delivreur_commande
				+ ", nom_receptionneur_commande=" + nom_receptionneur_commande + ", date_creation_commande="
				+ date_creation_commande + ", date_preparation_commande=" + date_preparation_commande
				+ ", date_retrait_commande=" + date_retrait_commande + ", accepter_ou_refuser_commande="
				+ accepter_ou_refuser_commande + ", liste_lignes=" + liste_lignes + ", produit_quantite="
				+ produit_quantite + ", entreprise=" + entreprise + ", fk_id_entreprise=" + fk_id_entreprise
				+ ", type_commande=" + type_commande + ", fk_id_type_commande=" + fk_id_type_commande
				+ ", utilisateurs=" + utilisateurs + ", liste_intervenants=" + liste_intervenants + "]";
	}
	
	
	
}
