// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Categorie_entreprise {
	/**
	 * relation one to many permet de retrouver tout les 
	 */
	public List<Produit> liste_produits;
	/**
	 * 
	 */
	private int id_categorie;
	/**
	 * 
	 */
	private String nom_categorie;


}
