// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Client {
	/**
	 * 
	 */
	private Integer id_client;
	/**
	 * 
	 */
	private String siret_client;
	
}
