// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class Compte {
	/**
	 * 
	 */
	private Integer id_compte;
	/**
	 * 
	 */
	private String login_compte;
	/**
	 * 
	 */
	private String password_compte;
	/**
	 * 
	 */
	private Utilisateur utilisateur;
	/**
	 * 
	 */
	private Integer id_utilisateur;
	
	public Compte() {
	}

	public Compte(Integer id_compte, String login_compte, String password_compte, Utilisateur utilisateur,
			Integer id_utilisateur) {
		this.id_compte = id_compte;
		this.login_compte = login_compte;
		this.password_compte = password_compte;
		this.utilisateur = utilisateur;
		this.id_utilisateur = id_utilisateur;
	}

	public Integer getId_compte() {
		return id_compte;
	}

	public void setId_compte(Integer id_compte) {
		this.id_compte = id_compte;
	}

	public String getLogin_compte() {
		return login_compte;
	}

	public void setLogin_compte(String login_compte) {
		this.login_compte = login_compte;
	}

	public String getPassword_compte() {
		return password_compte;
	}

	public void setPassword_compte(String password_compte) {
		this.password_compte = password_compte;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
		
		if(utilisateur != null) {
			this.id_utilisateur = utilisateur.getIdUtilisateur();
		}
		
		// doute
//		else {
//			
//			this.id_utilisateur = null;
//		}
		
	}

	public Integer getId_utilisateur() {
		return id_utilisateur;
	}

	public void setId_utilisateur(Integer id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}
	
	
	
}
