// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class FactureFinale extends BonCommande {
	/**
	 * 
	 */
	private Date date_creation_facture;
	/**
	 * 
	 */
	private float tva_facture;
	/**
	 * 
	 */
	private Type_facture type_facture;
	/**
	 * 
	 */
	private Integer id_type_facture;
	

}
