// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Lot {
	/**
	 * 
	 */
	private Integer id_lot;
	/**
	 * 
	 */
	private Produit lot_Produit;
	/**
	 * 
	 */
	private Date date_reception;
	/**
	 * 
	 */
	private Date date_peremption;
}
