// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Produit {
	/**
	 * 
	 */
	private Integer id_produit;
	private int code_barre_produit;
	private String designation_produit;
	private String description_product;
	private float poids_quantite;
	private float prix_unitaire_produit;
	
	
	/**
	 * relation many to one avec categorie
	 */
	private Categorie_produit categorie;
	/**
	 * foreign key id categorie
	 */
	private Integer fk_id_categorie;
	
	public Produit() {
	}

	public Produit(Integer id_produit, int code_barre_produit, String designation_produit, String description_product,
			float poids_quantite, float prix_unitaire_produit, Categorie_produit categorie) {
		super();
		this.id_produit = id_produit;
		this.code_barre_produit = code_barre_produit;
		this.designation_produit = designation_produit;
		this.description_product = description_product;
		this.poids_quantite = poids_quantite;
		this.prix_unitaire_produit = prix_unitaire_produit;
		this.categorie = categorie;
	}

	public Integer getId_produit() {
		return id_produit;
	}

	public void setId_produit(Integer id_produit) {
		this.id_produit = id_produit;
	}

	public int getCode_barre_produit() {
		return code_barre_produit;
	}

	public void setCode_barre_produit(int code_barre_produit) {
		this.code_barre_produit = code_barre_produit;
	}

	public String getDesignation_produit() {
		return designation_produit;
	}

	public void setDesignation_produit(String designation_produit) {
		this.designation_produit = designation_produit;
	}

	public String getDescription_product() {
		return description_product;
	}

	public void setDescription_product(String description_product) {
		this.description_product = description_product;
	}

	public float getPoids_quantite() {
		return poids_quantite;
	}

	public void setPoids_quantite(float poids_quantite) {
		this.poids_quantite = poids_quantite;
	}

	public float getPrix_unitaire_produit() {
		return prix_unitaire_produit;
	}

	public void setPrix_unitaire_produit(float prix_unitaire_produit) {
		this.prix_unitaire_produit = prix_unitaire_produit;
	}

	public Categorie_produit getCategorie() {
		return categorie;
	}

	public void setCategorie(Categorie_produit categorie) {
		this.categorie = categorie;
		
		if(categorie != null) {
			this.fk_id_categorie = categorie.getId_categorie();
		}
	}
	
	public Integer getFk_id_categorie() {
		return fk_id_categorie;
	}

	public void setFk_id_categorie(Integer fk_id_categorie) {
		this.fk_id_categorie = fk_id_categorie;
	}

	@Override
	public String toString() {
		return "Produit [id_produit=" + id_produit + ", code_barre_produit=" + code_barre_produit
				+ ", designation_produit=" + designation_produit + ", description_product=" + description_product
				+ ", poids_quantite=" + poids_quantite + ", prix_unitaire_produit=" + prix_unitaire_produit
				+ ", categorie=" + categorie + "]";
	}

	
	
}
