// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Promotion {
	/**
	 * 
	 */
	private Produit article;
	/**
	 * 
	 */
	public float pourcentage;
	
	public Date debut_promotion, fin_promotion;
}
