// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.HashMap;

/************************************************************/
/**
 * 
 */
public class Stock {
	/**
	 * 
	 */
	private Integer idStock;
	/**
	 * 
	 */
	private HashMap<Produit, Integer> stock_quantite_produit;
	//private List<Produit> article;
	/**
	 * 
	 */
	private int quantite;
	
}
