// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.List;

/************************************************************/
/**
 * 
 */
public class Utilisateur {

	private Integer idUtilisateur;
	private String nom_utilisateur, prenom_utilisateur;
	private List<Adresse> list_Addresse;
	private List<Role> liste_Roles;
	
	private String mdp;
	
	
	public Utilisateur() {}

	public Utilisateur(Integer idUtilisateur, List<Adresse> list_Addresse, List<Role> liste_Roles, String mdp) {
		super();
		this.idUtilisateur = idUtilisateur;
		this.list_Addresse = list_Addresse;
		this.liste_Roles = liste_Roles;
		this.mdp = mdp;
	}

	public Integer getIdUtilisateur() {
		return idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}
	
	public String getNom_utilisateur() {
		return nom_utilisateur;
	}

	public void setNom_utilisateur(String nom_utilisateur) {
		this.nom_utilisateur = nom_utilisateur;
	}

	public String getPrenom_utilisateur() {
		return prenom_utilisateur;
	}

	public void setPrenom_utilisateur(String prenom_utilisateur) {
		this.prenom_utilisateur = prenom_utilisateur;
	}

	public List<Adresse> getList_Addresse() {
		return list_Addresse;
	}

	public void setList_Addresse(List<Adresse> list_Addresse) {
		this.list_Addresse = list_Addresse;
	}

	public List<Role> getListe_Roles() {
		return liste_Roles;
	}

	public void setListe_Roles(List<Role> liste_Roles) {
		this.liste_Roles = liste_Roles;
	}

	public String getMdp() {
		return mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}
	
	
	
	

}
