// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

import model.BonCommande;
import outils.ConnectionDB;

/************************************************************/
/**
 * 
 */
public class DaoCommande implements Dao<BonCommande> {

	private Connection c;
	private ConnectionDB conn;
	private Statement stmt;
	private PreparedStatement pstmt;
	private ResultSet rs;
	
	public DaoCommande() {
		conn = new ConnectionDB();
		this.c = conn.getConnectionDB();
	}
	
	@Override
	public int create(BonCommande t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public BonCommande read(BonCommande t) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int update(BonCommande t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int delete(BonCommande t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public List<BonCommande> readAll() {
		// TODO Auto-generated method stub
		return null;
	}

	
	

}
