// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

import model.Role;
import outils.ConnectionDB;

/************************************************************/
/**
 * 
 */
public class DaoRole implements Dao<Role> {

	
	private Connection c;
	private ConnectionDB conn;
	private Statement stmt;
	private PreparedStatement pstmt;
	private ResultSet rs;
	
	public DaoRole() {
		conn = new ConnectionDB();
		this.c = conn.getConnectionDB();
	}
	
	@Override
	public int create(Role t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public Role read(Role t) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public int update(Role t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int delete(Role t) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public List<Role> readAll() {
		// TODO Auto-generated method stub
		return null;
	}
	

}
